version: '3'
services:

  main:
    image: node
    volumes:
      - ./main:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "8080:8080"
    depends_on:
      - frontend-react
      - frontend-angular

  frontend-react:
    image: node
    volumes:
      - ./frontend-react:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && PUBLIC_URL=http://localhost:3000/ npm run build && npm run serve"
    ports:
      - "3000:3000"

  frontend-angular:
    image: node
    volumes:
      - ./frontend-angular:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "4200:4200"
